config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :contracts, only: [:show, :new, :create] do
    member do
      get  'delivery_receipt'
      post 'delivery_receipt', to: 'contracts#create_delivery_receipt'
    end
    member do
      get  'devolution_receipt'
      post 'devolution_receipt', to: 'contracts#create_devolution_receipt'
    end
  end
  resources :clients, only: [:create, :index, :show, :new, :edit, :update]
  resources :tools, only: [:index]
  resources :prices, only: [:create, :index, :show, :new]
  resources :tools_groups
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :contracts

  validates :company_name, :fantasy_name, :cnpj, :contact_name, :phone, :email,
            :address, :address_number, :zipcode, :neighborhood, :city, :state,
            presence: true

  def to_s
    "#{fantasy_name} #{state}"
  end
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  has_and_belongs_to_many :tools
  has_one :delivery_receipt
  has_one :devolution_receipt
  belongs_to :client
  validates :client, :tools, :term, :initial_date, :deadline, :total_price,
            :delivery_address, :responsable, presence: true

  before_validation :set_deadline

  validates :term, inclusion: { in: Term::TERMS.values,
                                message: '%{value} não é um valor válido' }

  def print_tools
    tools.map(&:name).join(', ')
  end

  def format_date(date)
    date.strftime('%d/%m/%Y')
  end

  def delivery_receipt?
    delivery_receipt.present?
  end

  def devolution_receipt?
    devolution_receipt.present? && devolution_receipt.persisted?
  end

  def can_issue_devolution_receipt?
    delivery_receipt? && !devolution_receipt?
  end

  private

  def set_deadline
    self.deadline = initial_date + term.days if term
  end
end

app/models/delivery_receipt.rb
class DeliveryReceipt < ActiveRecord::Base
  belongs_to :contract
end

app/models/devolution_receipt.rb
class DevolutionReceipt < ActiveRecord::Base
  belongs_to :contract
  validates :employee, presence: true
end

app/models/no_price.rb
class NoPrice
  def price
    0
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  # before_validation :format_number

  belongs_to :tools_group
  validates :term, inclusion: { in: Term::TERMS.values,
                                message: '%{value} não é um valor válido' }

  def self.group_price
    ids = select('max(id) as id').group('term, tools_group_id')
    all.where(id: ids).order('tools_group_id, term')
  end


  # def format_number
  #   self.price = self.price.gsub(/[^\d,.]/, '').gsub(/[,.]/, '.' => '', ',' => '.')
  # end
end

app/models/term.rb
class Term
  TERMS = { "1 dia": 1,
            "3 dias": 3,
            "1 semana": 7,
            "1 quinzena": 15,
            "1 mês": 30,
            "3 meses": 90 }
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_and_belongs_to_many :contracts
  belongs_to :tools_group

  delegate :price_by_term, to: :tools_group
end

app/models/tools_group.rb
class ToolsGroup < ActiveRecord::Base
  has_many :tools
  has_many :prices
  validates :name, presence: true

  def price_by_term(term)
    # TODO: alterar deadline para term
    prices.where(deadline: term).last || NoPrice.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :show]
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to @client
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client
    else
      render :edit
    end
  end

  def show
  end

  private

  def client_params
    params.require(:client)
      .permit(:company_name, :cnpj, :contact_name, :phone, :email,
              :address, :address_number, :aditional_address_detail,
              :zipcode, :neighborhood, :city, :state, :fantasy_name)
  end

  def set_client
    @client = Client.find(params[:id])
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show]
  before_action :set_collections, only: [:show, :new, :create]

  def show
  end

  def new
    @contract = Contract.new
    @prices = Price.all
  end

  def create
    @contract = Contract.new(contract_params)
    @prices = Price.all
    if @contract.save
      redirect_to @contract
    else
      flash[:warning] = 'Atenção! Todos os campos são obrigatórios.'
      render :new
    end
  end

  private

  def set_collections
    @clients = Client.all
    @tools = Tool.all
    @terms = Term::TERMS
  end

  def set_contract
    @contract = Contract.find(params[:id])
  end

  def contract_params
    params.require(:contract)
      .permit(:client_id, :term, :initial_date,
              :delivery_address, :responsable, tool_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @clients = Client.all
    @tools = Tool.all
    @contracts = Contract.all
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  def index
    @prices = Price.group_price
  end

  def new
    @tools_group = ToolsGroup.all
    @terms = Term::TERMS
    @price = Price.new(term: params[:term], tools_group_id: params[:tool_group])
  end

  def create
    @price = Price.new(price_params)
    if @price.save
      redirect_to @price
    else
      flash[:warning] = 'Não foi possível salvar tabela de preços'
      render :new
    end
  end

  def show
    @price = Price.find(params[:id])
  end

  private

  def price_params
    strong_params = params.require(:price).permit(:price, :term, :tools_group_id)
    strong_params[:price] = strong_params[:price].gsub(/[^\d,.]/, '')
                            .gsub(/[,.]/, '.' => '', ',' => '.')
    strong_params
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.all
  end
end

app/controllers/tools_groups_controller.rb
class ToolsGroupsController < ApplicationController
  before_action :set_tools, only: [:edit, :update, :show, :destroy]

  def index
    @toolsgroup = ToolsGroup.all
  end

  def edit
  end

  def new
    @toolsgroup = ToolsGroup.new
  end

  def show
  end

  def destroy
    @toolsgroup .destroy
    flash[:success] = 'Grupo excluido com sucesso'
    redirect_to tools_groups_path
  end

  def create
    @toolsgroup = ToolsGroup.new(tools_params)
    if @toolsgroup.save
      redirect_to @toolsgroup
    else
      flash[:warning] = 'Não foi possível salvar grupo de ferramentas'
      render :new
    end
  end

  def update
    if @toolsgroup.update(tools_params)
      redirect_to @toolsgroup
    else
      flash[:warning] = 'Atenção! Todos os campos são obrigatórios.'
      render :edit
    end
  end

  private

  def tools_params
    params.require(:tools_group).permit(:name, :description)
  end

  def set_tools
    @toolsgroup = ToolsGroup.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BRAZILIAN_STATES = [%w(Acre AC),
                      %w(Alagoas AL),
                      %w(Amapá AP),
                      %w(Amazonas AM),
                      %w(Bahia BA),
                      %w(Ceará CE),
                      %w(Distrito\ Federal DF),
                      %w(Espírito\ Santo ES),
                      %w(Goiás GO),
                      %w(Maranhão MA),
                      %w(Mato\ Grosso MT),
                      %w(Mato\ Grosso\ do\ Sul MS),
                      %w(Minas\ Gerais MG),
                      %w(Pará PA),
                      %w(Paraíba PB),
                      %w(Paraná PR),
                      %w(Pernambuco PE),
                      %w(Piauí PI),
                      %w(Rio\ de\ Janeiro RJ),
                      %w(Rio\ Grande\ do\ Norte RN),
                      %w(Rio\ Grande\ do\ Sul RS),
                      %w(Rondônia RO),
                      %w(Roraima RR),
                      %w(Santa\ Catarina SC),
                      %w(São\ Paulo SP),
                      %w(Sergipe SE),
                      %w(Tocantins TO)
                     ] unless const_defined?('BRAZILIAN_STATES')
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client do |f| %>
  <%= f.input :company_name, label: 'Razão Social' %>
  <%= f.input :fantasy_name, label: 'Nome Fantasia' %>
  <%= f.input :cnpj, label: 'CNPJ' %>
  <%= f.input :contact_name, label: 'Nome do contato' %>
  <%= f.input :phone, label: 'Telefone' %>
  <%= f.input :email, label: 'E-mail' %>
  <%= f.input :address, label: 'Logradouro' %>
  <%= f.input :address_number, label: 'Número', as: :string %>
  <%= f.input :aditional_address_detail, label: 'Complemento' %>
  <%= f.input :zipcode, label: 'CEP'%>
  <%= f.input :neighborhood, label: 'Bairro'%>
  <%= f.input :city, label: 'Cidade'%>
  <%= f.input :state, label: 'Estado', collection: ApplicationHelper::BRAZILIAN_STATES, prompt: "Escolha um Estado" %>
  <%= f.button :submit, submit_text, class:"btn btn-primary"  %>
<% end  %>

app/views/clients/edit.html.erb
<%= render partial: 'form', locals: {submit_text: 'Atualizar Cliente'} %>

app/views/clients/index.html.erb
<div class="page-header">
   <h1>Lista de Clientes</h1>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
      <table id="clients" class='table table-striped'>
        <thead>
          <tr>
            <th>Nome Fantasia</th>
            <th>CNPJ</th>
            <th>Estado</th>
          </tr>
        </thead>
        <tbody>
          <% @clients.each do |client| %>
          <tr>
            <td><%= link_to client.fantasy_name, client %></td>
            <td><%= client.cnpj %></td>
            <td><%= client.state %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Novo', new_client_path,class: "btn btn-success pull-right" %>
  </div>
</div>

app/views/clients/new.html.erb
<%= render partial: 'form', locals: {submit_text: 'Criar Cliente'} %>

app/views/clients/show.html.erb
<div class="page-header">
  <h1>Cliente <%= @client.fantasy_name %> <%= @client.state %></h1>
</div>

<dl id="client-details" class="dl-horizontal">
  <dt>Razão Social</dt>
  <dd><%= @client.company_name %></dd>
  <dt>CNPJ</dt>
  <dd><%= @client.cnpj %></dd>
  <dt>Nome Fantasia</dt>
  <dd><%= @client.fantasy_name %></dd>
  <dt>Lougradouro</dt>
  <dd><%= @client.address %></dd>
  <dt>Número</dt>
  <dd><%= @client.address_number %></dd>
  <dt>Complemento</dt>
  <dd><%= @client.aditional_address_detail %></dd>
  <dt>CEP</dt>
  <dd><%= @client.zipcode %></dd>
  <dt>Bairro</dt>
  <dd><%= @client.neighborhood %></dd>
  <dt>Cidade</dt>
  <dd><%= @client.city %></dd>
  <dt>Estado</dt>
  <dd><%= @client.state %></dd>
  <dt>Nome do contato</dt>
  <dd><%= @client.contact_name %></dd>
  <dt>Telefone</dt>
  <dd><%= @client.phone %></dd>
  <dt>E-mail</dt>
  <dd><%= @client.email %></dd>
</dl>

app/views/contracts/_delivery_receipt.html.erb
<% if !@contract.delivery_receipt? %>
  <%= link_to 'Emitir Recibo de Entrega', delivery_receipt_contract_path, method: :post, class: "btn btn-primary" %>
<% else %>
  <%= link_to 'Visualizar Recibo de Entrega', delivery_receipt_contract_path, class: "btn btn-primary" %>
<% end %>

app/views/contracts/_devolution_receipt.html.erb
<% if @contract.can_issue_devolution_receipt? %>
  <%= form_tag devolution_receipt_contract_path, { class: "form-inline" } do %>
    <div class="form-group">
      <%= label_tag(:employee, "Funcionário") %>
      <%= text_field_tag(:employee, "", class:"form-control") %>
    </div>
      <%= submit_tag 'Emitir Recibo de Devolução', class:"btn btn-primary" %>
  <% end %>
<% elsif @contract.delivery_receipt? %>
  <%= link_to 'Visualizar Recibo de Devolução', devolution_receipt_contract_path, class: "btn btn-primary" %>
<% end %>

app/views/contracts/delivery_receipt.html.erb
<div class="row">
  <div class="col-md-8 col-sm-8 text-center">
    <h1 class="text-center"> Recibo de Entrega </h1>
    <br>
    <% today = @contract.delivery_receipt.created_at %>
    <h4 class="text-center"> <%= "São Paulo, #{today.day}/#{today.month}/#{today.year}" %> </h4>
    <br>
    <p class="text-justify">
      Eu, <strong><%= @contract.responsable %></strong> (nome do responsável),
      em nome da empresa <strong><%= @contract.client.company_name %></strong>
      (razão social), inscrita no CNPJ <strong><%= @contract.client.cnpj %></strong>
      declaro ter recebido os equipamentos <% @contract.tools.each do |tool| %>
      <strong><%= "#{tool.serial_number} #{tool.name}" %></strong><% end %>
      (lista dos equipamentos contendo número de série e nome) pelo período de <strong><%= @contract.term %> dias</strong> em perfeitas
      condições de uso no endereço <strong><%= @contract.delivery_address %></strong>
      (endereço de entrega) no dia <strong><%= @contract.initial_date.strftime('%d/%m/%Y') %></strong> (data da emissão)
      de acordo com o contrato <strong>2016001</strong> (número do contrato).
    </p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <p class="text-left">
      ______________________________
      <br>
      <strong>Assinatura do Responsável</strong>
    </p>
  </div>
</div>

app/views/contracts/devolution_receipt.html.erb
<div class="row">
  <div class="col-md-8 col-sm-8 text-center">
    <h1 class="text-center"> Recibo de Devolução </h1>
    <br>
    <% today = @contract.delivery_receipt.created_at %>
    <h4 class="text-center"> <%= "São Paulo, #{today.day}/#{today.month}/#{today.year}" %> </h4>
    <br>
    <p class="text-justify">
      Eu, <strong><%= @contract.devolution_receipt.employee %></strong> (nome do funcionário da RentEquip), declaro ter recebido os equipamentos
      <% @contract.tools.each do |tool| %> <strong><%= "#{tool.serial_number} #{tool.name}" %></strong><% end %>
      (lista dos equipamentos contendo número de série e nome) em devolução referente ao contrato <strong>2016001</strong>
      (número do contrato) em perfeitas condições da empresa <strong><%= @contract.client.company_name %></strong> (razão social),
      inscrita no CNPJ <strong><%= @contract.client.cnpj %></strong> no dia <strong><%= @contract.deadline.strftime('%d/%m/%Y') %></strong> (data de devolução).
    </p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <p class="text-left">
      ______________________________
      <br>
      <strong>Assinatura do Funcionário</strong>
    </p>
  </div>
</div>

app/views/contracts/new.html.erb
<div class="row">
  <div class="col-md-12">
    <% if flash[:warning] %>
    <div class="alert alert-danger" role="alert">
      <span class="error_message"><%= flash[:warning] %></span>
    </div>
    <% end %>
  </div>
</div>

<div class="row">
  <%= simple_form_for @contract do |f| %>
  <%= f.association :client, label: "Cliente", label_method: lambda { |client| "#{client.fantasy_name} #{client.state}".html_safe }, value_method: :id, class: "col-md-12 col-sm-12", error: "Campo obrigatório" %>
  <%= f.input :tool_ids, label: "Equipamento(s)", required: true, wrapper_html: { class: "#{'has-error' if f.object.errors.messages[:tools].present?}" } do %>
    <%= f.select :tool_ids, @tools.map { |t| [ "#{t.serial_number} #{t.name}", t.id, { data:{tools_group_id: t.tools_group_id} }] }, {}, {multiple:true, class: "form-control required", required: true} %>
    <% if f.object.errors.messages[:tools].present? %>
      <span class="help-block">Campo obrigatório</span>
    <% end %>
  <% end %>
  <%= f.input :term, label: "Prazo", collection: @terms, prompt: "Selecione um prazo", error: "Campo obrigatório" %>
  <%= f.input :initial_date, label: "Data inicial", as: :date, html5: true, input_html: { value: Time.zone.now.strftime('%d/%m/%Y') }, error: "Campo obrigatório"%>
  <%= f.input :total_price, label: "Preço do contrato", error: "Campo obrigatório", as: :string %>
  <%= f.input :delivery_address, label: "Endereço de entrega", error: "Campo obrigatório" %>
  <%= f.input :responsable, label: "Responsável", error: "Campo obrigatório" %>
  <%= f.button :submit, 'Emitir Contrato', class:"btn btn-primary"  %>
  <% end %>
</div>
<script>
  var prices = <%= @prices.to_json.html_safe %>;
</script>

app/views/contracts/show.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="page-header">
      <h1>Contrato
        <%= @contract.id %></h1>
      <!-- TODO: alterar para numero do contrato quando criar o campo -->
    </div>
    <dl class="dl-horizontal">
      <dt>Empresa</dt>
      <dd><%= "#{@contract.client.fantasy_name} #{@contract.client.state}" %></dd>
      <dt>Ferramentas</dt>
      <% @contract.tools.each do |tool| %>
      <dd><%= "#{tool.serial_number} #{tool.name}" %></dd>
      <% end %>
      <dt>Prazo</dt>
      <dd><%= @contract.term %></dd>
      <dt>Data Inicial</dt>
      <dd><%= @contract.initial_date.strftime("%d/%m/%Y") %></dd>
      <dt>Data Final</dt>
      <dd><%= @contract.deadline.strftime("%d/%m/%Y") %></dd>
      <dt>Total</dt>
      <dd><%= number_to_currency(@contract.total_price, unit: "R$ ", separator: ",", delimiter: ".") %></dd>
      <dt>Endereço de Entrega</dt>
      <dd><%= @contract.delivery_address %></dd>
      <dt>Responsável</dt>
      <dd><%= @contract.responsable %></dd>
    </dl>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <%= render partial: 'delivery_receipt' %>
  </div>
  <div class="col-md-9">
    <%= render partial: 'devolution_receipt' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="container">
      <h3>Lista de Contratos</h3>
      <table id="contratos" class='table table-striped'>
        <thead>
          <tr>
            <th>Número de Contrato</th>
            <th>Dono do contrato</th>
            <th>Equipamentos</th>
            <th>Quantidade de Equipamentos</th>
            <th>Expiração do Contrato</th>
            <th>Valor do Contrato</th>
          </tr>
        </thead>
        <tbody>
          <% @contracts.each do |contract| %>
          <tr>
            <td class="text-center"><%= link_to '2016001', contract %></td>
            <td class="text-center"><%= "#{contract.client.fantasy_name} #{contract.client.state}" %></td>
            <td class="text-center"><%= contract.print_tools %></td>
            <td class="text-center"><%= contract.tools.count %></td>
            <td class="text-center"><%= contract.format_date(contract.deadline) %></td>
            <td class="text-center"><%= number_to_currency(contract.total_price, unit: "R$ ", delimiter: ".", separator: ",") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>Rent Equip</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <%= link_to "Rent Equip", root_path, {class:"navbar-brand"} %>
          </div>
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Emitir Contrato", new_contract_path %>
            </li>
            <li>
              <%= link_to "Clientes", clients_path %>
            </li>
            <li>
              <%= link_to "Equipamentos", tools_path %>
            </li>
            <li>
              <%= link_to "Grupo de Ferramentas", tools_groups_path %>
            </li>
            <li>
              <%= link_to "Preços", prices_path %>
            </li>
            <li>
              <%= link_to 'Grupo de Equipamentos', tools_groups_path %>
            </li>
          </ul>
        </div>
      </nav>

      <div class="row">
        <% if flash[:success] %>
        <div class="col-md-12 col-sm-12">
          <div class="alert alert-success alert-dismissible pull-right" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">x</span>
            </button>
            <%= flash[:success] %>
          </div>
        </div>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/prices/_form.html.erb
<%= simple_form_for @price do |f| %>
  <%= f.input :price, label: 'Preço' %>
  <%= f.input :tools_group_id, label: "Grupo de Equipamentos", collection: @tools_group, prompt: "Selecione um grupo", error: "Campo obrigatório"%>
  <%= f.input :term, label: "Prazo", collection: @terms, prompt: "Selecione um Prazo", error: "Campo obrigatório"%>
  <%= f.button :submit, submit_btn, class:"btn btn-primary"  %>
<% end  %>

app/views/prices/edit.html.erb
<%= render partial: 'form', locals: {submit_btn: 'Atualizar'} %>

app/views/prices/index.html.erb
<div class="row">
  <div class="col-md-10 col-sm-10">
      <h3>Lista de Preços</h3>
  </div>
  <div class="col-md-2 col-sm-2">
    <h3><%= link_to 'Novo', new_price_path, class: "btn btn-success pull-right" %></h3>
  </div>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <table class = 'table table-striped'>
      <thead>
        <tr>
          <th> Preço </th>
          <th> Grupo de equipamentos </th>
          <th> Prazo </th>
        </tr>
      </thead>
      <tbody>
        <% @prices.each do |price|%>
        <tr>
          <td><%= link_to "%0.2f" % price.price, price %></td>
          <td><%= link_to price.tools_group.name, price %></td>
          <td><%= link_to price.term, price %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/prices/new.html.erb
<%= render partial: 'form', locals: {submit_btn: 'Salvar'} %>

app/views/prices/show.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="page-header">
      <h1><%= number_to_currency(@price.price, unit: "R$ ", separator: ",", delimiter: "") %></h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <dl class="dl-horizontal">
      <dt>Grupo de Equipamentos</dt>
      <dd><%= @price.tools_group.name %></dd>
      <dt>Prazo</dt>
      <dd><%= @price.term %></dd>
    </dl>
    <%= link_to 'Atualizar', new_price_path(tool_group: @price.tools_group.id, term: @price.term),class: "btn btn-primary" %>
  </div>
</div>

app/views/tools/index.html.erb
<!-- <% @tools.each do |tool| %>
  <%= tool.name %>
  <%= tool.description %>
  <%= tool.serial_number %>
  <%= tool.tools_group.name %>
  <%= tool.status %>
<% end %> -->


<div class="page-header">
   <h1>Lista de Equipamentos</h1>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
      <table id="equipamentos" class='table table-striped'>
        <thead>
          <tr>
            <th>Nome do Equipamento</th>
            <th>Descrição</th>
            <th>Grupo de Equipamentos</th>
            <th>Serial</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @tools.each do |tool| %>
          <tr>
            <td><%= tool.name %></td>
            <td><%= tool.description %></td>
            <td><%= tool.serial_number %></td>
            <td><%= tool.tools_group.name %></td>
            <td><%= tool.status %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/tools_groups/_form.html.erb
<div class="row">
  <% if flash[:warning] %>
  <div class="col-md-12 col-sm-12">
    <div class="alert alert-danger alert-dismissible pull-right" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">x</span>
      </button>
      <%=flash[:warning] %>
    </div>
  </div>
  <% end %>
</div>
<%= simple_form_for @toolsgroup do |f|%>
  <%= f.input :name, label: 'Nome',  error: 'O campo não pode estar vazio', placeholder: 'Insira o nome do grupo aqui.' %>
  <%= f.input :description, label: 'Descrição', placeholder: 'Insira a descrição referente do grupo de equipamentos.' %>
  <%= f.button :submit, submit_btn, class: "btn-primary" %>
<% end %>

app/views/tools_groups/edit.html.erb
<%= render partial: "form", locals: {submit_btn: 'Atualizar'} %>

app/views/tools_groups/index.html.erb
<div class="page-header">
  <h1>Grupos de Equipamentos</h1>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <table class = 'table table-striped'>
      <thead>
        <tr>
          <th> Nome </th>
          <th> Descrição </th>
        </tr>
      </thead>
      <tbody>
        <% @toolsgroup.each do |group|%>
          <tr>
            <td><%= link_to group.name, group %></td>
            <td><%= link_to group.description, group %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <%= link_to 'Novo', new_tools_group_path,class: "btn btn-success pull-right" %>
  </div>
</div>

app/views/tools_groups/new.html.erb
<%= render partial: "form", locals: {submit_btn: 'Salvar'} %>

app/views/tools_groups/show.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="page-header">
      <h1><%= @toolsgroup.name %></h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <dl class="dl-horizontal">
      <dt>Descrição</dt>
      <dd><%= @toolsgroup.description %></dd>
    </dl>
    <%= link_to 'Atualizar', edit_tools_group_path(@toolsgroup),class: "btn btn-primary" %>
    <%= link_to 'Excluir', tools_group_path(@toolsgroup), method: :delete, class: "btn btn-danger" unless @toolsgroup.tools.any? %>
  </div>
</div>